//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VIT.Entity.HealthCare
{
    public partial class Facility
    {
        public Facility()
        {
            this.Charges = new Collection<Charge>();
            this.Doctors = new Collection<Doctor>();
            this.Drugs = new Collection<Drug>();
            this.Instruments = new Collection<Instrument>();
            this.Patients = new Collection<Patient>();
            this.Users = new Collection<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual Collection<Charge> Charges { get; set; }
        public virtual Collection<Doctor> Doctors { get; set; }
        public virtual Collection<Drug> Drugs { get; set; }
        public virtual Collection<Instrument> Instruments { get; set; }
        public virtual Collection<Patient> Patients { get; set; }
        public virtual Collection<User> Users { get; set; }
    }
    
}
