//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VIT.Entity.HealthCare
{
    public partial class Patient
    {
        public Patient()
        {
            this.Charges = new Collection<Charge>();
            this.ChargeDrugs = new Collection<ChargeDrug>();
            this.ChargeInstruments = new Collection<ChargeInstrument>();
            this.Clinicals = new Collection<Clinical>();
        }
    
        public int Id { get; set; }
        public int FacilityId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public Nullable<System.DateTime> DateOnSet { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    
        public virtual Collection<Charge> Charges { get; set; }
        public virtual Collection<ChargeDrug> ChargeDrugs { get; set; }
        public virtual Collection<ChargeInstrument> ChargeInstruments { get; set; }
        public virtual Collection<Clinical> Clinicals { get; set; }
        public virtual Facility Facility { get; set; }
    }
    
}
