//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using VIT.Entity.HealthCare;

namespace VIT.DataAccessLayer.HealthCare.Data
{
    public partial class HealthCareEntities : DbContext
    {
        public HealthCareEntities(string connectionString) :
            base(new System.Data.Objects.ObjectContext(new System.Data.EntityClient.EntityConnection(DataHelper.LinqHelper.Global.GetMetaData("VITData"),
    			new System.Data.SqlClient.SqlConnection(connectionString))), true)
        {
    		(this as IObjectContextAdapter).ObjectContext.DefaultContainerName = "HealthCareEntities";
    		this.Configuration.ProxyCreationEnabled = false;
    		this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Charge> Charges { get; set; }
        public DbSet<CPT> CPTs { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<Drug> Drugs { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<ICD> ICDs { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
